spring:
  mail:
    host: smtp.gmail.com
    port: 587
    username: sgm3takoyaki@gmail.com
    password: gauawjhlmkgtsnbw
    protocol: smtp
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
          ssl:
            trust: smtp.gmail.com
