spring:
  mail:
    host: smtp.gmail.com
    port: 587
    username: example@gmail.com # change here
    password: examplePassword  # change here
    protocol: smtp
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
          ssl:
            trust: smtp.gmail.com
